return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   config = function()
  --     require("lspconfig").yamlls.setup({
  --       yaml = {
  --         editor = {
  --           tabSize = 2,
  --         },
  --         format = {
  --           singleQuote = true,
  --         },
  --         hover = true,
  --         completion = true,
  --         customTags = {
  --           "!fn",
  --           "!And",
  --           "!If",
  --           "!Not",
  --           "!Equals",
  --           "!Or",
  --           "!FindInMap sequence",
  --           "!Base64",
  --           "!Cidr",
  --           "!Ref",
  --           "!Ref Scalar",
  --           "!Sub",
  --           "!GetAtt",
  --           "!GetAZs",
  --           "!ImportValue",
  --           "!Select",
  --           "!Split",
  --           "!Join sequence",
  --         },
  --       },
  --     })
  --     -- Configuration here, or leave empty to use defaults)
  --   end,
  -- },
}
